# Generated by Django 4.1.2 on 2022-10-11 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='idade',
            field=models.IntegerField(default=18, max_length=3),
        ),
    ]
