# Generated by Django 4.1.2 on 2022-10-11 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_professor_idade'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='descricao',
            field=models.TextField(default='Nenhuma descrição foi adicionada até o momento!'),
        ),
        migrations.AddField(
            model_name='professor',
            name='nome',
            field=models.CharField(default='Nenhum nome foi adicionada até o momento!', max_length=100),
        ),
        migrations.AddField(
            model_name='professor',
            name='valor_hora',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=9),
        ),
        migrations.AlterField(
            model_name='professor',
            name='foto',
            field=models.URLField(default='Nenhuma foto foi adicionada até o momento!', max_length=255),
        ),
        migrations.AlterField(
            model_name='professor',
            name='idade',
            field=models.IntegerField(default=19),
        ),
    ]
